# Generated by Django 4.2.7 on 2023-11-15 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0002_auto_20231111_1435"),
        ("users", "0003_rm_unused_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stories.agent",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_completion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="set_current_completion",
                to="stories.storycompletion",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stories.story",
            ),
        ),
    ]
