# Generated by Django 3.2.9 on 2023-11-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInteraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.agent')),
            ],
        ),
        migrations.CreateModel(
            name='StoryCompletion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='AgentInteractionMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('role', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.agentinteraction')),
            ],
        ),
        migrations.AddField(
            model_name='agentinteraction',
            name='story_completion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.storycompletion'),
        ),
    ]
