# Generated by Django 4.2.7 on 2023-11-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0003_remove_story_cover_prompt_story_cover_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="story",
            old_name="solution",
            new_name="extensive_solution",
        ),
        migrations.RenameField(
            model_name="story",
            old_name="description",
            new_name="prelude",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="prompt",
        ),
        migrations.AddField(
            model_name="agent",
            name="agent_type",
            field=models.TextField(default="SUSPECT"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="alibi",
            field=models.TextField(default="No alibi"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="background",
            field=models.TextField(default="No defined background"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="character",
            field=models.TextField(default="No defined character"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="hidden",
            field=models.TextField(default="No defined hidden info"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="knowledge",
            field=models.TextField(default="No defined knowledge"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="relationships",
            field=models.TextField(default="No defined relationships"),
            preserve_default=False,
        ),
    ]
